name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore ConsoleCalculator.sln
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test ConsoleCalculator.sln --configuration Debug --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
